//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = module.exports = {};
if (typeof js === 'undefined') {
  js = {};
}
if (typeof js.droid_stalker === 'undefined') {
  js.droid_stalker = {};
}
if (typeof js.droid_stalker.thrift === 'undefined') {
  js.droid_stalker.thrift = {};
}
js.droid_stalker.thrift.AndroidAppStruct = module.exports.AndroidAppStruct = function(args) {
  this.packageName = null;
  this.activityName = null;
  this.applicationName = null;
  this.applicationIcon = null;
  if (args) {
    if (args.packageName !== undefined) {
      this.packageName = args.packageName;
    }
    if (args.activityName !== undefined) {
      this.activityName = args.activityName;
    }
    if (args.applicationName !== undefined) {
      this.applicationName = args.applicationName;
    }
    if (args.applicationIcon !== undefined) {
      this.applicationIcon = args.applicationIcon;
    }
  }
};
js.droid_stalker.thrift.AndroidAppStruct.prototype = {};
js.droid_stalker.thrift.AndroidAppStruct.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.packageName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.activityName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.applicationName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.applicationIcon = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

js.droid_stalker.thrift.AndroidAppStruct.prototype.write = function(output) {
  output.writeStructBegin('AndroidAppStruct');
  if (this.packageName !== null && this.packageName !== undefined) {
    output.writeFieldBegin('packageName', Thrift.Type.STRING, 1);
    output.writeString(this.packageName);
    output.writeFieldEnd();
  }
  if (this.activityName !== null && this.activityName !== undefined) {
    output.writeFieldBegin('activityName', Thrift.Type.STRING, 2);
    output.writeString(this.activityName);
    output.writeFieldEnd();
  }
  if (this.applicationName !== null && this.applicationName !== undefined) {
    output.writeFieldBegin('applicationName', Thrift.Type.STRING, 3);
    output.writeString(this.applicationName);
    output.writeFieldEnd();
  }
  if (this.applicationIcon !== null && this.applicationIcon !== undefined) {
    output.writeFieldBegin('applicationIcon', Thrift.Type.STRING, 4);
    output.writeString(this.applicationIcon);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

