/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rc.droid_stalker.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Kernel exception error codes
 */
public enum AppExceptionErrorCode implements org.apache.thrift.TEnum {
  ERROR_WHILE_EXECUTING_CODE(1);

  private final int value;

  private AppExceptionErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AppExceptionErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return ERROR_WHILE_EXECUTING_CODE;
      default:
        return null;
    }
  }
}
